# Generated by Django 4.2.7 on 2023-11-09 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_meals',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menu',
        ),
        migrations.CreateModel(
            name='MenuMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_app.meal')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='meal_app.menu')),
            ],
            options={
                'db_table': 'menu_meals',
            },
        ),
    ]
